### ISSUE TITLE
run with a small error

### ISSUE THREAD

**Issue by yuanshuoastro** [somogyijanos/cursor-chat-export#14]
Hello, 

Just find it looks like:

./chat.py discover --help
Traceback (most recent call last):
  File "/Users/.../.../cursor-chat-export/./chat.py", line 7, in <module>
    from src.export import ChatExporter, MarkdownChatFormatter, MarkdownFileSaver
  File "/Users/.../.../.../cursor-chat-export/src/export.py", line 92
    user_text.append(f"[selections]  \n{"\n".join([s["text"] for s in bubble['selections']])}")
                                          ^
SyntaxError: unexpected character after line continuation character

The python env over my MacOS is python3.11

Thank you.

**Comment by somogyijanos** [comment]
This is bc I was using Python 3.12 where backslashes are allowed in f strings already. If you switch to Python 3.12, this error should be gone.
